;**********************************************************************
;                                                                     *
;    Filename:	    mtxv4.inc                                         *
;    Date:                                                            *
;    File Version:                                                    *
;                                                                     *
;    Author:        el@jap.hu                                         *
;    Www page:      http://jap.hu/electronic/                         *
;                                                                     * 
;                                                                     *
;**********************************************************************
;    Notes:
;
; RF transmitter prot.v4 (Manchester)
;**********************************************************************

	EXTERN mtx_buffer, mtx_delay
	EXTERN mtx_init, mtx_send
